server:
  port: 8081

spring:
  application:
    name: backend-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://${host.ip}:${host.port}/${mysql.db}
    username: { mysql.user }
    password: { mysql.pass }
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

# Cấu hình giới hạn dung lượng file upload